services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: clothing-inspection-backend/Dockerfile
    dockerContext: ./clothing-inspection-backend
    envVars:
      - fromGroup: production-env      # ↩️ Render → Environment Group에 생성해 두세요
    autoDeploy: true
    healthCheckPath: /api/healthz

  - type: static
    name: frontend
    env: static
    plan: free
    buildCommand: cd clothing-inspection-frontend && npm ci && npm run build
    staticPublishPath: clothing-inspection-frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ap-002.onrender.com
    routes:
      - type: rewrite
        source: "/api/*"
        destination: "https://ap-002.onrender.com/api/:splat"

  - type: mysql
    name: db
    plan: free
    properties:
      databaseName: clothing_inspection
      user: clothing_user

# Note: 1) create an Environment Group named 'production-env' in Render
#       2) populate all variables (DB_PASSWORD, JWT_SECRET, SMTP_*, etc.)
#       3) frontend REACT_APP_API_URL should match backend service URL
